#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 3 16:27:02 2020

@author: GS
"""

from pandas_datareader import data as data

PG = data.DataReader('PG', data_source='yahoo', start='2000-1-1')

PG.head()
PG.tail()

PG['simple_return'] = (PG['Adj Close'] / PG['Adj Close'].shift(1)) - 1
print(PG['simple_return'])

import matplotlib.pyplot as plt

PG['simple_return'].plot(figsize=(8, 5))
plt.show()


avg_returns_d = PG['simple_return'].mean()
avg_returns_d

avg_returns_y = PG['simple_return'].mean() * 250
avg_returns_y

print(str(round(avg_returns_y, 5) * 100) + '%')
